// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview An AI chatbot for answering questions about Çamlıca Köyü.
 *
 * - camlicaAIChatbot - A function that handles the chatbot interactions.
 * - CamlicaAIChatbotInput - The input type for the camlicaAIChatbot function.
 * - CamlicaAIChatbotOutput - The return type for the camlicaAIChatbot function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CamlicaAIChatbotInputSchema = z.object({
  question: z.string().describe('The question about Çamlıca Köyü.')
});
export type CamlicaAIChatbotInput = z.infer<typeof CamlicaAIChatbotInputSchema>;

const CamlicaAIChatbotOutputSchema = z.object({
  answer: z.string().describe('The answer to the question about Çamlıca Köyü.')
});
export type CamlicaAIChatbotOutput = z.infer<typeof CamlicaAIChatbotOutputSchema>;

export async function camlicaAIChatbot(input: CamlicaAIChatbotInput): Promise<CamlicaAIChatbotOutput> {
  return camlicaAIChatbotFlow(input);
}

const prompt = ai.definePrompt({
  name: 'camlicaAIChatbotPrompt',
  input: {schema: CamlicaAIChatbotInputSchema},
  output: {schema: CamlicaAIChatbotOutputSchema},
  model: 'googleai/gemini-1.5-flash-latest',
  prompt: `As an AI assistant for Çamlıca village in Domaniç, Turkey, please answer the following question about the village. Your response MUST be in Turkish.

Question: {{{question}}}

Here are some detailed facts about the village to help you:

GENERAL INFORMATION:
- Çamlıca is a village in Domaniç, Kütahya Province, Turkey.
- Population: 425 people (199 male, 226 female) as of 2024.
- Village headman (muhtar): Numan YAŞAR.
- Located 8 km from Domaniç town center and 85 km from Kütahya city center.
- Elevation: 810 meters.
- The village was formerly known as "Göçebe" until around 1955.
- The village is home to a 1000-year-old pine tree called "Mızık Çamı" (previously known as Hasan Çamı).

ECONOMY:
- The village economy is based on agriculture and animal husbandry.
- It's doing better economically than many other villages in Domaniç.

GEOGRAPHY & HISTORY:
- The village is centrally located in Domaniç.
- It has roots dating back to the early Ottoman Empire.
- Founded by Yörük nomads. The name was changed from "Göçebe" (nomad) to "Çamlıca" (pine-covered place) by a teacher around 1955, inspired by the surrounding pine forests.

Please provide a helpful, informative and accurate response based on this data. You are a chatbot for Çamlıca village, designed to answer questions about the village's history, culture, geography, and community.`,
  config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_ONLY_HIGH',
      },
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_NONE',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_LOW_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_CIVIC_INTEGRITY',
        threshold: 'BLOCK_ONLY_HIGH',
      },
    ],
  },
});

const camlicaAIChatbotFlow = ai.defineFlow(
  {
    name: 'camlicaAIChatbotFlow',
    inputSchema: CamlicaAIChatbotInputSchema,
    outputSchema: CamlicaAIChatbotOutputSchema,
  },
  async input => {
    try {
        const {output} = await prompt(input);
        if (!output || !output.answer) {
            console.error("[camlicaAIChatbotFlow] AI chatbot did not return a valid output. Output was:", output);
            return { answer: "Yapay zeka geçerli bir yanıt oluşturamadı. Lütfen sorunuzu farklı bir şekilde sormayı deneyin." };
        }
        return {answer: output.answer};
    } catch (error: any) {
        console.error("[camlicaAIChatbotFlow] Error during AI generation:", error);
        // Instead of throwing an error that crashes the client, return a friendly message in the output schema.
        return { answer: "Yapay zeka yanıtı oluşturulurken bir sunucu hatası oluştu. Lütfen tekrar deneyin veya farklı bir soru sorun." };
    }
  }
);
