
// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview An AI chatbot for answering questions about Çamlıca Köyü.
 *
 * - camlicaAIChatbot - A function that handles the chatbot interactions.
 * - CamlicaAIChatbotInput - The input type for the camlicaAIChatbot function.
 * - CamlicaAIChatbotOutput - The return type for the camlicaAIChatbot function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { gemini15Flash } from 'genkit/models';

const CamlicaAIChatbotInputSchema = z.object({
  question: z.string().describe('The question about Çamlıca Köyü.')
});
export type CamlicaAIChatbotInput = z.infer<typeof CamlicaAIChatbotInputSchema>;

const CamlicaAIChatbotOutputSchema = z.object({
  answer: z.string().describe('The answer to the question about Çamlıca Köyü.')
});
export type CamlicaAIChatbotOutput = z.infer<typeof CamlicaAIChatbotOutputSchema>;

export async function camlicaAIChatbot(input: CamlicaAIChatbotInput): Promise<CamlicaAIChatbotOutput> {
  return camlicaAIChatbotFlow(input);
}

const prompt = ai.definePrompt({
  name: 'camlicaAIChatbotPrompt',
  input: {schema: CamlicaAIChatbotInputSchema},
  output: {schema: CamlicaAIChatbotOutputSchema},
  model: gemini15Flash,
  prompt: `As an AI assistant for Çamlıca village in Domaniç, Turkey, please answer the following question about the village:\n\nQuestion: {{{question}}}\n\nHere are some detailed facts about the village to help you:\n\nGENERAL INFORMATION:\n- Çamlıca is a village in Domaniç, Kütahya Province, Turkey
- Population: 425 people (199 male, 226 female) as of 2024
- Village headman (muhtar): Numan YAŞAR
- Located 8 km from Domaniç town center and 85 km from Kütahya city center
- Elevation: 810 meters
- The village was formerly known as "Göçebe" until 1928 (some sources say until 1955)
- The village has a 1000-year-old pine tree called "Hasan Çamı"

ECONOMY:
- The village economy is worth approximately 2.6 million USD (90 million TL)
- Per capita income is around 238,000 TL, which is below Turkish standards
- Despite this, Çamlıca is doing better than most other villages in Domaniç

GEOGRAPHY:
- The village is a central village in Domaniç with many cars passing through
- The total area is approximately a 20 km², which is larger than the Fatih district of Istanbul

HISTORY:
- The village has roots dating back to the early Ottoman Empire period
- In the 16th and 17th centuries, the village was established as Ottomans expanded
- Yörük nomads (8-9 families) settled in the area
- 3-4 families settled in what is now Yeşilköy due to water access
- 4-5 families settled in pine-covered Çamlıca
- 2-3 families settled in forested Kozluca
- The name was changed from "Göçebe" (meaning "nomad") to "Çamlıca" (referring to the pine trees) around 1955 by a teacher
- The village has grown to become the central village of Domaniç
- Much of this history is oral tradition passed down through generations with no written records

Please provide a helpful, informative and accurate response in Turkish language. You are specifically designed as a chatbot for Çamlıca village to answer questions about the village's history, culture, geography, and community.`,
  config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_ONLY_HIGH',
      },
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_NONE',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_LOW_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_CIVIC_INTEGRITY',
        threshold: 'BLOCK_ONLY_HIGH',
      },
    ],
  },
});

const camlicaAIChatbotFlow = ai.defineFlow(
  {
    name: 'camlicaAIChatbotFlow',
    inputSchema: CamlicaAIChatbotInputSchema,
    outputSchema: CamlicaAIChatbotOutputSchema,
  },
  async input => {
    try {
        const {output} = await prompt(input);
        if (!output || !output.answer) {
            throw new Error("AI chatbot did not return a valid output.");
        }
        return {answer: output.answer};
    } catch (error: any) {
        // Log the full error on the server for debugging, but don't send raw error to client.
        console.error("[camlicaAIChatbotFlow] Error during AI generation:", error);
        
        // Re-throw a generic, client-safe error message.
        // This prevents Next.js from throwing a server error due to complex/internal error objects.
        throw new Error("Yapay zeka yanıtı oluşturulurken bir sunucu hatası oluştu. Lütfen tekrar deneyin veya farklı bir soru sorun.");
    }
  }
);
